# Archivo _config.yml para tu proyecto Jekyll

# Información básica del sitio
title: "Atlas Interactivo de Programación en Python"
description: "Un libro para aprender Python desde cero"
baseurl: "/Atlas_interactivo_de_programacion_en_Python" 
url: "https://eduardoleon9010.github.io/Atlas_interactivo_de_programacion_en_Python" # Cambia esta URL si necesitas

# Tema de Jekyll (opcional, usa el predeterminado si no configuras otro)
theme: minima

# Directorios personalizados
collections_dir: _pages # Carpeta donde están las páginas principales
layout: default # Layout predeterminado para todas las páginas

# Plugins opcionales (si necesitas características adicionales)
plugins:
  - jekyll-feed # Genera un feed RSS para el sitio
  - jekyll-seo-tag # Mejora el SEO de las páginas
  - jekyll-sitemap # Genera un mapa del sitio automáticamente

# Ignorar ciertos archivos
exclude:
  - README.md
  - LICENSE
  - CONTRIBUTING.md

# Permitir Markdown para páginas
markdown: kramdown
highlighter: rouge

# Configuración de rutas
permalink: pretty # URLs legibles (por ejemplo, /conceptos-basicos en lugar de /conceptos-basicos.html)
